[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "*"
    Access-Control-Allow-Headers = "*"

[build]
	publish = "/"

[dev]
	publish = "/"
	port= 8080



[functions]
	directory = "functions"
	node_bundler = "esbuild" 
	included_files = ["./src/datatable/*.json"]
