[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "*"
    Access-Control-Allow-Headers = "*"


[functions]

 directory = "myfunctions/"
included_files = ["datatable/*.json"]

